# -*- coding: utf-8 -*-
"""phi.audio.media_keys — system-wide media key interception + Now Playing.

Two layers working together:

1. NSEvent global monitor (always-on)
   Intercepts NSEventMaskSystemDefined events with subtype=8 — the raw
   hardware events generated by the Touch Bar / F-key media keys regardless
   of which app has focus.  No Accessibility permission required.

2. MPRemoteCommandCenter (system integration)
   Registers phi as the active "Now Playing" app so the OS routes media keys
   here by priority, Control Center shows the current track, and lock-screen
   controls appear.  Falls back silently if the framework refuses (sandboxed
   or restricted environments).

3. MPNowPlayingInfoCenter (metadata display)
   Updates title / artist / album / position / playback rate so Control
   Center, lock screen, and AirPlay receivers show live metadata.

Usage
-----
    handler = MediaKeyHandler(
        on_play_pause = app.on_play_pause,
        on_next       = app.on_next,
        on_prev       = app.on_prev,
        on_vol_up     = lambda: app._vol_step(+0.05),
        on_vol_down   = lambda: app._vol_step(-0.05),
        on_mute       = app.on_toggle_mute,
        schedule      = app.after,
    )
    handler.start()

    # When a track loads:
    handler.update_now_playing(meta, position=0.0, is_playing=True)

    # During _poll or on pause/play:
    handler.set_playback_state(position, is_playing)

    # On shutdown:
    handler.stop()
"""
from __future__ import annotations

import queue
import threading
from typing import Callable

# Pre-load pyobjc Objective-C frameworks on the importing (main) thread.
#
# pyobjc's lazy importer calls load_cftypes() the first time any symbol from
# a framework is accessed.  If that first access happens inside the
# phi-media-keys background thread while the main event loop is running,
# the CoreFoundation initialisation path is entered from a non-main thread
# → SIGBUS on macOS (bus error).
#
# Importing these modules here forces the full framework load to complete on
# the main thread, before MediaKeyHandler.start() spawns its NSRunLoop thread.
# The try/except means this is a no-op on Linux/Windows.
try:
    from AppKit import NSEvent, NSEventMaskSystemDefined  # type: ignore[import]  # noqa: F401
    from Foundation import NSRunLoop, NSDate              # type: ignore[import]  # noqa: F401
except Exception:
    pass


# ── keycodes emitted by NSEvent subtype=8 ────────────────────────────────────
_KEY_PLAY_PAUSE = 16
_KEY_NEXT       = 19
_KEY_PREV       = 20
_KEY_VOL_UP     = 14    # intercepted by OS but we surface it for UI sync
_KEY_VOL_DOWN   = 13
_KEY_MUTE       = 7


class _NowPlayingWorker:
    """Single daemon thread that owns every ``setNowPlayingInfo_`` IPC write.

    The macOS Now Playing daemon can stall for hundreds of milliseconds (or
    more) when Control Center or AirPlay is active.  Calling it on the Qt main
    thread causes the beachball.  This worker decouples the write: callers
    post a zero-argument callable via :meth:`submit` and return immediately;
    the worker drains the queue on a private background thread.

    Position-only updates are coalesced: when the queue already contains a
    pending position update, the newer one replaces it so the daemon never
    receives a burst of stale positions.  Full metadata writes are always
    delivered in order.
    """

    _TAG_FULL = "full"
    _TAG_POS  = "pos"

    def __init__(self) -> None:
        self._q: queue.SimpleQueue = queue.SimpleQueue()
        self._t = threading.Thread(
            target=self._run, daemon=True, name="phi-nowplaying",
        )
        self._t.start()

    def submit_full(self, fn: "Callable[[], None]") -> None:
        """Post a full-metadata write.  Never dropped."""
        self._q.put((self._TAG_FULL, fn))

    def submit_pos(self, fn: "Callable[[], None]") -> None:
        """Post a position-only write.  Coalesced if one is already pending."""
        self._q.put((self._TAG_POS, fn))

    def stop(self) -> None:
        """Signal the worker to exit after draining any pending items."""
        self._q.put(None)

    def _run(self) -> None:
        while True:
            item = self._q.get()
            if item is None:
                return
            tag, fn = item

            if tag == self._TAG_POS:
                # Drain: drop stale position entries, stop at any full-meta entry.
                latest_fn = fn
                extra: "tuple | None" = None
                while True:
                    try:
                        nxt = self._q.get_nowait()
                    except queue.Empty:
                        break
                    if nxt is None:
                        # Shutdown sentinel arrived mid-drain — finish then exit.
                        try:
                            latest_fn()
                        except Exception:
                            pass
                        return
                    nxt_tag, nxt_fn = nxt
                    if nxt_tag == self._TAG_POS:
                        latest_fn = nxt_fn  # drop older position write
                    else:
                        extra = nxt          # full-meta — deliver after position
                        break
                fn = latest_fn

            try:
                fn()
            except Exception:
                pass

            if extra is not None:
                _, efn = extra
                try:
                    efn()
                except Exception:
                    pass


class MediaKeyHandler:
    """
    Intercepts hardware media keys and keeps the system Now Playing state
    in sync with phi's playback engine.

    All callbacks are dispatched on the Tk main thread via *schedule*
    (root.after), so they are safe to call UI methods directly.
    """

    def __init__(
        self,
        *,
        on_play_pause: Callable,
        on_next:       Callable,
        on_prev:       Callable,
        on_vol_up:     Callable | None = None,
        on_vol_down:   Callable | None = None,
        on_mute:       Callable | None = None,
        schedule:      Callable,          # schedule(ms, fn) — posts fn to main thread
    ) -> None:
        self._cbs = {
            "play_pause": on_play_pause,
            "next":       on_next,
            "prev":       on_prev,
            "vol_up":     on_vol_up,
            "vol_down":   on_vol_down,
            "mute":       on_mute,
        }
        self._schedule = schedule
        self._monitor  = None
        self._thread:  threading.Thread | None = None
        self._running  = False

        # Cache of the NowPlaying info dict.  Written from both the main thread
        # (set_playback_state) and a background thread (update_now_playing) so
        # access is guarded by _np_lock.
        self._np_cache: dict = {}
        self._np_lock = threading.Lock()

        # All setNowPlayingInfo_ IPC writes are delegated to this worker so
        # the macOS NowPlaying daemon never stalls the Qt main thread.
        self._np_worker = _NowPlayingWorker()

    # ── lifecycle ─────────────────────────────────────────────────────────────

    def start(self) -> None:
        """
        Install the NSEvent global monitor and register MPRemoteCommandCenter.

        Must be called from the main thread.

        NSEvent global monitors are serviced by the *application's* main run
        loop — not by a secondary thread's NSRunLoop.  Running a secondary
        NSRunLoop to service them causes a SIGBUS on macOS because the global
        event tap is tied to the main-thread Cocoa event dispatch path.

        The monitor is therefore installed here, synchronously on the main
        thread.  Tk's Cocoa integration services it automatically.  No
        background thread is needed or started.
        """
        self._running = True
        self._install_global_monitor()
        self._register_remote_commands()

    def stop(self) -> None:
        """Remove the event monitor and clear Now Playing state.

        Signals the :class:`_NowPlayingWorker` to drain and exit. Now Playing
        clear is queued on that worker — never call setNowPlayingInfo_ on the
        main thread (it stalls). The worker join is skipped on purpose.
        """
        self._running = False
        try:
            from AppKit import NSEvent
            if self._monitor is not None:
                NSEvent.removeMonitor_(self._monitor)
                self._monitor = None
        except Exception:
            pass
        try:
            def _clear() -> None:
                import MediaPlayer as MP
                MP.MPNowPlayingInfoCenter.defaultCenter().setNowPlayingInfo_(None)
            self._np_worker.submit_full(_clear)
        except Exception:
            pass
        self._np_worker.stop()

    # ── NSEvent global monitor (layer 1) ──────────────────────────────────────

    def _install_global_monitor(self) -> None:
        """
        Install NSEvent global monitor on the calling (main) thread.

        The handler fires on the main thread via Tk's Cocoa event dispatch —
        no secondary NSRunLoop required.
        """
        try:
            from AppKit import NSEvent, NSEventMaskSystemDefined

            def _handle(event):
                try:
                    if event.subtype() != 8:
                        return
                    data     = event.data1()
                    keycode  = (data & 0xFFFF0000) >> 16
                    keyflags = (data & 0xFF00) >> 8
                    key_down = bool(keyflags & 0x1)
                    if not key_down:
                        return
                    self._dispatch(keycode)
                except Exception:
                    pass

            self._monitor = NSEvent.addGlobalMonitorForEventsMatchingMask_handler_(
                NSEventMaskSystemDefined,
                _handle,
            )

        except Exception:
            pass   # Graceful degradation if AppKit unavailable

    def _dispatch(self, keycode: int) -> None:
        mapping = {
            _KEY_PLAY_PAUSE: "play_pause",
            _KEY_NEXT:       "next",
            _KEY_PREV:       "prev",
            _KEY_VOL_UP:     "vol_up",
            _KEY_VOL_DOWN:   "vol_down",
            _KEY_MUTE:       "mute",
        }
        name = mapping.get(keycode)
        if name and self._cbs.get(name):
            self._schedule(0, self._cbs[name])

    # ── MPRemoteCommandCenter (layer 2) ───────────────────────────────────────

    def _register_remote_commands(self) -> None:
        """
        Register with MPRemoteCommandCenter so the OS routes media keys to phi
        by priority and Control Center buttons call our handlers.
        """
        try:
            import MediaPlayer as MP

            cc = MP.MPRemoteCommandCenter.sharedCommandCenter()

            def _play(event):
                self._schedule(0, self._cbs["play_pause"])
                return MP.MPRemoteCommandHandlerStatusSuccess

            def _pause(event):
                self._schedule(0, self._cbs["play_pause"])
                return MP.MPRemoteCommandHandlerStatusSuccess

            def _toggle(event):
                self._schedule(0, self._cbs["play_pause"])
                return MP.MPRemoteCommandHandlerStatusSuccess

            def _next(event):
                self._schedule(0, self._cbs["next"])
                return MP.MPRemoteCommandHandlerStatusSuccess

            def _prev(event):
                self._schedule(0, self._cbs["prev"])
                return MP.MPRemoteCommandHandlerStatusSuccess

            cc.playCommand().setEnabled_(True)
            cc.pauseCommand().setEnabled_(True)
            cc.togglePlayPauseCommand().setEnabled_(True)
            cc.nextTrackCommand().setEnabled_(True)
            cc.previousTrackCommand().setEnabled_(True)

            cc.playCommand().addTargetWithHandler_(_play)
            cc.pauseCommand().addTargetWithHandler_(_pause)
            cc.togglePlayPauseCommand().addTargetWithHandler_(_toggle)
            cc.nextTrackCommand().addTargetWithHandler_(_next)
            cc.previousTrackCommand().addTargetWithHandler_(_prev)

            # Disable commands we don't handle so they don't steal events
            cc.changePlaybackRateCommand().setEnabled_(False)
            cc.seekForwardCommand().setEnabled_(False)
            cc.seekBackwardCommand().setEnabled_(False)

        except Exception:
            pass   # Graceful degradation

    # ── MPNowPlayingInfoCenter (layer 3) ──────────────────────────────────────

    def update_now_playing(
        self,
        meta:       dict,
        *,
        position:   float = 0.0,
        is_playing: bool  = False,
    ) -> None:
        """
        Push track metadata to the system Now Playing info center.

        Safe to call from any thread (including the main thread).  The dict
        is built on the calling thread (cheap); the actual ``setNowPlayingInfo_``
        IPC write — and the potentially-slow ``NSImage`` artwork creation — are
        both delegated to :class:`_NowPlayingWorker` so neither can stall the UI.
        """
        try:
            import MediaPlayer as MP

            info: dict = {
                MP.MPMediaItemPropertyTitle:
                    meta.get("title") or "",
                MP.MPMediaItemPropertyArtist:
                    meta.get("artist") or "",
                MP.MPMediaItemPropertyAlbumTitle:
                    meta.get("album") or "",
                MP.MPMediaItemPropertyPlaybackDuration:
                    float(meta.get("duration") or 0),
                MP.MPNowPlayingInfoPropertyElapsedPlaybackTime:
                    float(position),
                MP.MPNowPlayingInfoPropertyPlaybackRate:
                    1.0 if is_playing else 0.0,
            }

            art_bytes = meta.get("art_bytes")

            # Cache the metadata dict immediately (without artwork) so
            # set_playback_state can build on it from the main thread.
            with self._np_lock:
                self._np_cache = dict(info)

            _info = dict(info)  # snapshot for the closure

            def _write(info: dict = _info, art: bytes | None = art_bytes) -> None:
                if art:
                    artwork = MediaKeyHandler._make_artwork(art)
                    if artwork is not None:
                        info[MP.MPMediaItemPropertyArtwork] = artwork
                try:
                    import MediaPlayer as _MP
                    _MP.MPNowPlayingInfoCenter.defaultCenter().setNowPlayingInfo_(info)
                except Exception:
                    pass

            self._np_worker.submit_full(_write)
        except Exception:
            pass

    def set_playback_state(self, position: float, is_playing: bool) -> None:
        """
        Lightweight update — refreshes playback position + rate without
        rebuilding the full info dict.

        Non-blocking: builds the info dict on the calling thread (cheap),
        then posts the actual ``setNowPlayingInfo_`` IPC write to the
        background :class:`_NowPlayingWorker`.  The main thread is never
        stalled by the macOS NowPlaying daemon.
        """
        try:
            import MediaPlayer as MP
            with self._np_lock:
                info = dict(self._np_cache)
            info[MP.MPNowPlayingInfoPropertyElapsedPlaybackTime] = float(position)
            info[MP.MPNowPlayingInfoPropertyPlaybackRate] = 1.0 if is_playing else 0.0
            with self._np_lock:
                self._np_cache = info

            _info = info  # close over snapshot so the lambda is safe

            def _write() -> None:
                try:
                    import MediaPlayer as _MP
                    _MP.MPNowPlayingInfoCenter.defaultCenter().setNowPlayingInfo_(_info)
                except Exception:
                    pass

            self._np_worker.submit_pos(_write)
        except Exception:
            pass

    @staticmethod
    def _make_artwork(art_bytes: bytes):
        """Convert raw JPEG/PNG bytes to MPMediaItemArtwork.  Returns None on failure."""
        try:
            import MediaPlayer as MP
            from AppKit import NSImage, NSData
            import objc

            ns_data  = NSData.dataWithBytes_length_(art_bytes, len(art_bytes))
            ns_image = NSImage.alloc().initWithData_(ns_data)
            if ns_image is None:
                return None

            def provider(size):
                return ns_image

            artwork = MP.MPMediaItemArtwork.alloc().initWithBoundsSize_requestHandler_(
                (512, 512), provider
            )
            return artwork
        except Exception:
            return None
