"""Bus tasks: graph vault writes — ingest, link, annotate, ingest-source."""
from __future__ import annotations

from typing import Any

from mcp_server.bus._task_registry import task


@task("graph.ingest")
def graph_ingest(
    source_dir: str,
    dry_run: bool = False,
    max_files: int = 500,
) -> dict[str, Any]:
    from pathlib import Path

    from graph.node import VAULT_ROOT
    from workers.oesophagus import ingest

    source = Path(source_dir).expanduser().resolve()
    if not source.exists():
        return {"error": "source_not_found", "source_dir": str(source)}
    if not source.is_dir():
        return {"error": "source_not_a_directory", "source_dir": str(source)}
    result = ingest(
        source=source, vault_root=VAULT_ROOT, max_files=max_files, dry_run=dry_run,
    )
    summary = result.summary()
    summary["pulse_home"] = min(result.n_ingested * 0.05, 1.5) if not dry_run else 0.0
    return summary


@task("graph.ingest_source")
def graph_ingest_source(
    packages: str = "",
    dry_run: bool = False,
    output_subdir: str = "source",
) -> dict[str, Any]:
    from pathlib import Path

    from graph.ingestion import IngestionPipeline, write_import_index
    from graph.node import VAULT_ROOT
    from graph.source_extractor import scan_source

    pkg_list = [p.strip() for p in packages.split(",") if p.strip()] or None
    scan = scan_source(packages=pkg_list)
    if not scan.docs:
        return {
            "error": "no_docs_extracted",
            "skipped": scan.skipped[:20],
            "packages_scanned": pkg_list or "all",
        }
    if dry_run:
        return {
            "dry_run": True,
            "would_write": len(scan.docs),
            "skipped": len(scan.skipped),
            "sample_titles": [d.title for d in scan.docs[:10]],
        }

    output_dir = VAULT_ROOT / output_subdir
    pipeline = IngestionPipeline(
        output_dir=output_dir,
        threshold=0.25,
        top_k=5,
        cross_link=True,
    )
    manifest = pipeline.run(scan.docs)

    pkg_stems: dict[str, list[str]] = {}
    for node in manifest.nodes:
        pkg = node.stem.split("-")[0] if "-" in node.stem else output_subdir
        pkg_stems.setdefault(pkg, []).append(node.stem)

    for pkg, stems in pkg_stems.items():
        idx_path = output_dir / f"{pkg}-index.md"
        link_lines = "\n".join(f"→ [[{s}]]" for s in sorted(stems))
        idx_content = (
            f"# {pkg} — source index\n\n"
            f"#hub #{pkg} #code #source\n\n"
            f"> {len(stems)} modules ingested.\n\n---\n\n"
            f"## Modules\n\n{link_lines}\n\n---\n\n"
            f"→ [[CODE]] ← code hub  \n"
            f"→ [[phi]] — player / library graph  \n"
            f"→ [[graph]] — graph worker hub\n\n"
            f"*Generated by `graph_ingest_source`*\n"
        )
        idx_path.write_text(idx_content, encoding="utf-8")

    write_import_index(output_dir, [n.stem for n in manifest.nodes], "source modules")
    from graph.layers import dedupe_index_stems
    dedupe_index_stems(VAULT_ROOT)

    hub_counts = dict(manifest.hub_counts)
    if not dry_run:
        try:
            from graph.tracker import record_stems
            record_stems([n.stem for n in manifest.nodes], "amended")
        except Exception:
            pass

    return {
        "ingested": manifest.n_written,
        "skipped_scan": len(scan.skipped),
        "backend": manifest.backend,
        "output_dir": str(output_dir.relative_to(VAULT_ROOT)),
        "hub_distribution": hub_counts,
        "sample_nodes": [n.stem for n in manifest.nodes[:8]],
        "pulse_hubs": hub_counts,
        "pulse_scale": 0.08,
    }


@task("graph.link")
def graph_link(threshold: float = 0.25) -> dict[str, Any]:
    from graph.worker import run_link

    report = run_link(threshold=threshold)
    return {
        "n_nodes_modified": report.n_nodes_modified,
        "n_new_links": report.n_new_links,
        "modified": [
            {"node": stem, "new_links": links}
            for stem, links in report.modified
        ],
        "touch_harmonic": True,
    }


@task("graph.annotate")
def graph_annotate(
    target_stem: str,
    comment: str,
    tool_context: str = "",
    confidence: float = 0.75,
) -> dict[str, Any]:
    from graph.node import VAULT_ROOT, write_comment_node

    path = write_comment_node(
        target_stem=target_stem,
        comment=comment,
        tool_context=tool_context,
        confidence=confidence,
    )
    return {
        "written":      str(path.relative_to(VAULT_ROOT)),
        "target":       target_stem,
        "confidence":   confidence,
        "tool_context": tool_context or None,
    }
