# -*- coding: utf-8 -*-
"""phi.models.dragon_curve — Dragon curve geometric scoring (pure numpy).

The dragon curve is generated by the recursive fold rule:
    seq(k) = seq(k-1) + [1] + reverse_complement(seq(k-1))
where 1=right-turn, 0=left-turn. This produces a self-similar space-filling
curve whose fold-bit sequence is a natural coarse-to-fine positional encoding.

Geometric variables (from scribble-002, prompt 3):
    D1  — direction vector of the nearest segment to query point (x, y)
    D2  — y-component of the midpoint of the *next* segment  ("vertical slice")
    D3  — absolute 2D endpoint of the next segment
    D4_A = ‖D3‖ / ‖D1‖ − D2      rotation-invariant norm-ratio   [regression TARGET]
    D4_B = |D3·d_⊥| / ‖D1‖ − D2   local-frame fold projection    [XGBoost FEATURE]
    d_⊥  = unit normal to D1 (perpendicular in the local fold frame)

Usage:
    dc = DragonCurve(depth=8)           # 256 segments, 8-bit fold vectors
    d4_a, d4_b, bits = dc.score(0.42, 0.37)
    batch_target = dc.rolling_d4_a(xy_batch, window=16)
"""
from __future__ import annotations

import numpy as np
from typing import Tuple


# ─────────────────────────────────────────────────────────────────────────────
# Fold sequence & curve generation
# ─────────────────────────────────────────────────────────────────────────────

def _generate_fold_sequence(depth: int) -> np.ndarray:
    """
    Dragon curve fold sequence for the given depth.

    depth=1 → [1]  (1 turn, 2 segments)
    depth=k → 2^k − 1 turns, 2^k segments

    Rule: seq(k) = seq(k-1) ++ [1] ++ reverse_complement(seq(k-1))
          complement: 0 ↔ 1

    Returns:
        np.ndarray shape (2^depth − 1,), dtype int8, values in {0, 1}
    """
    if depth == 0:
        return np.array([], dtype=np.int8)
    seq: np.ndarray = np.array([1], dtype=np.int8)
    for _ in range(depth - 1):
        seq = np.concatenate([seq, [1], (1 - seq)[::-1]])
    return seq


# Direction table: east, north, west, south (counterclockwise order).
# Index encodes current heading; modular arithmetic handles turns.
_DIRS = np.array([[1, 0], [0, 1], [-1, 0], [0, -1]], dtype=np.float64)


def _fold_seq_to_points(fold_seq: np.ndarray) -> np.ndarray:
    """
    Convert a fold sequence to 2D curve vertices.

    fold_seq of length L  →  L+2 points  (L+1 segments)

    Conventions:
        fold_bit = 1  →  right turn (clockwise):     dir = (dir − 1) % 4
        fold_bit = 0  →  left turn  (counterclockwise): dir = (dir + 1) % 4

    Returns:
        np.ndarray shape (L + 2, 2), dtype float64
    """
    n_pts = len(fold_seq) + 2
    points = np.empty((n_pts, 2), dtype=np.float64)
    dir_idx: int = 0            # start heading east
    pos = np.zeros(2, dtype=np.float64)
    points[0] = pos
    pos = pos + _DIRS[dir_idx]
    points[1] = pos

    for i, bit in enumerate(fold_seq):
        dir_idx = (dir_idx - 1) % 4 if bit == 1 else (dir_idx + 1) % 4
        pos = pos + _DIRS[dir_idx]
        points[i + 2] = pos

    return points


# ─────────────────────────────────────────────────────────────────────────────
# DragonCurve
# ─────────────────────────────────────────────────────────────────────────────

class DragonCurve:
    """
    Dragon curve geometric scorer.

    Args:
        depth: fold depth ∈ [1, 12].
               depth=8  → 256 segments, 8-bit fold vectors (matches 256-d BERT).
               depth=9  → 512 segments, 9-bit fold vectors (matches 512-d CLAP).
    """

    def __init__(self, depth: int = 8) -> None:
        if not (1 <= depth <= 12):
            raise ValueError(f"depth must be in [1, 12], got {depth}")
        self.depth = depth
        self._fold_seq = _generate_fold_sequence(depth)
        self._points = _fold_seq_to_points(self._fold_seq)

        # Bounding box for normalising external (x, y) ∈ [0, 1]² into curve space
        self._bb_min: np.ndarray = self._points.min(axis=0)
        self._bb_max: np.ndarray = self._points.max(axis=0)
        self._bb_range: np.ndarray = np.maximum(self._bb_max - self._bb_min, 1e-9)

        # Segment midpoints — used for nearest-segment lookup
        self._seg_mids: np.ndarray = (self._points[:-1] + self._points[1:]) / 2

    # ── Properties ────────────────────────────────────────────────────────────

    @property
    def n_segments(self) -> int:
        return len(self._points) - 1

    @property
    def points(self) -> np.ndarray:
        """Read-only view of curve vertices, shape (n_segments+1, 2)."""
        return self._points.view()

    # ── Coordinate helpers ────────────────────────────────────────────────────

    def unit_to_curve(self, x: float, y: float) -> Tuple[float, float]:
        """Map (x, y) ∈ [0, 1]² to the curve's bounding box."""
        return (
            float(self._bb_min[0] + x * self._bb_range[0]),
            float(self._bb_min[1] + y * self._bb_range[1]),
        )

    def nearest_segment(self, x: float, y: float) -> int:
        """Index of the curve segment whose midpoint is nearest to (x, y)."""
        q = np.array([x, y], dtype=np.float64)
        dists = np.sum((self._seg_mids - q) ** 2, axis=1)
        return int(np.argmin(dists))

    # ── Fold bits ─────────────────────────────────────────────────────────────

    def fold_bits(self, seg_idx: int) -> np.ndarray:
        """
        Return a fixed-length binary feature vector for segment seg_idx.

        The vector contains the `depth` fold bits immediately preceding the
        segment (zero-padded at the start for early segments).

        Returns:
            np.ndarray shape (depth,), dtype float32, values in {0.0, 1.0}
        """
        bits = np.zeros(self.depth, dtype=np.float32)
        n = min(seg_idx, self.depth)
        if n > 0:
            bits[:n] = self._fold_seq[seg_idx - n : seg_idx].astype(np.float32)
        return bits

    # ── Geometric variables D1 / D2 / D3 ─────────────────────────────────────

    def d1_d2_d3(
        self, seg_idx: int
    ) -> Tuple[np.ndarray, float, np.ndarray]:
        """
        Compute D1, D2, D3 for the segment pair at seg_idx.

            D1 = direction vector of segment seg_idx               shape (2,)
            D2 = y-component of midpoint of segment seg_idx+1      scalar
            D3 = 2D endpoint of segment seg_idx+1                  shape (2,)

        Clamps to the penultimate segment pair when seg_idx is near the end.

        Returns:
            D1: np.ndarray (2,)
            D2: float
            D3: np.ndarray (2,)
        """
        i = min(seg_idx, self.n_segments - 2)
        p0 = self._points[i]
        p1 = self._points[i + 1]
        p2 = self._points[i + 2]

        D1 = p1 - p0
        D2 = float((p1[1] + p2[1]) * 0.5)   # y-component of seg i+1 midpoint
        D3 = p2.copy()
        return D1, D2, D3

    # ── Scoring ───────────────────────────────────────────────────────────────

    @staticmethod
    def score_a(D1: np.ndarray, D2: float, D3: np.ndarray) -> float:
        """
        D4_A = ‖D3‖ / ‖D1‖ − D2

        Norm-ratio score. Rotation-invariant. This is the regression TARGET.
        """
        n1 = float(np.linalg.norm(D1))
        if n1 < 1e-9:
            return 0.0
        return float(np.linalg.norm(D3)) / n1 - D2

    @staticmethod
    def score_b(D1: np.ndarray, D2: float, D3: np.ndarray) -> float:
        """
        D4_B = |D3 · d_⊥| / ‖D1‖ − D2_⊥

        Local-frame projection score. d_⊥ is the unit normal to D1 (the fold
        direction). D2_⊥ is the projection of the seg i+1 midpoint onto d_⊥,
        approximated from D2 and d_⊥.

        Axis-dependent — encodes fold direction. Used as an XGBoost FEATURE.
        """
        n1 = float(np.linalg.norm(D1))
        if n1 < 1e-9:
            return 0.0
        d = D1 / n1
        d_perp = np.array([-d[1], d[0]], dtype=np.float64)

        D3_proj = float(np.dot(D3, d_perp))
        # Approximate D2_perp: midpoint.y is D2; midpoint.x is unknown here.
        # Use the y-component of d_perp to project the scalar D2 contribution.
        D2_perp = float(D2 * d_perp[1])

        return abs(D3_proj) / n1 - D2_perp

    def score(
        self,
        x: float,
        y: float,
        normalized: bool = True,
    ) -> Tuple[float, float, np.ndarray]:
        """
        Full geometric score for a single query point.

        Args:
            x, y:       query coordinates
            normalized: True → (x, y) ∈ [0, 1]², mapped to curve bbox first

        Returns:
            d4_a:      float          — norm-ratio score    (regression target)
            d4_b:      float          — fold-direction score (XGBoost feature)
            fold_bits: ndarray (depth,) — binary positional encoding
        """
        if normalized:
            x, y = self.unit_to_curve(x, y)
        seg = self.nearest_segment(x, y)
        D1, D2, D3 = self.d1_d2_d3(seg)
        return self.score_a(D1, D2, D3), self.score_b(D1, D2, D3), self.fold_bits(seg)

    def score_batch(
        self,
        xy: np.ndarray,
        normalized: bool = True,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Score a batch of (x, y) points.

        Args:
            xy:         np.ndarray shape (N, 2)
            normalized: see score()

        Returns:
            d4_a:      ndarray (N,)
            d4_b:      ndarray (N,)
            fold_bits: ndarray (N, depth)
        """
        assert xy.ndim == 2 and xy.shape[1] == 2, f"Expected (N, 2), got {xy.shape}"
        N = len(xy)
        a_vals = np.empty(N, dtype=np.float64)
        b_vals = np.empty(N, dtype=np.float64)
        bit_mat = np.empty((N, self.depth), dtype=np.float32)
        for i in range(N):
            a_vals[i], b_vals[i], bit_mat[i] = self.score(
                float(xy[i, 0]), float(xy[i, 1]), normalized=normalized
            )
        return a_vals, b_vals, bit_mat

    def rolling_d4_a(
        self,
        xy: np.ndarray,
        window: int = 16,
        normalized: bool = True,
    ) -> np.ndarray:
        """
        Causal rolling mean of D4_A over a batch of (x, y) points.

        Args:
            xy:         ndarray shape (N, 2)
            window:     rolling window size
            normalized: see score()

        Returns:
            ndarray shape (N,) — rolling mean of D4_A (causal, no lookahead)
        """
        a_vals, _, _ = self.score_batch(xy, normalized=normalized)
        N = len(a_vals)
        cs = np.cumsum(a_vals)
        result = np.empty(N, dtype=np.float64)
        result[:window] = cs[:window] / np.arange(1, min(window + 1, N + 1))
        if N > window:
            result[window:] = (cs[window:] - cs[:N - window]) / window
        return result
